-- Convert notas_fiscais.id and razao.id from UUID to BIGINT

-- notas_fiscais (inbound FK from critica.nota_fiscal_id)
DO $$
BEGIN
  IF EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_schema = 'public' AND table_name = 'notas_fiscais'
    AND column_name = 'id' AND data_type = 'uuid'
  ) THEN
    ALTER TABLE public.notas_fiscais ADD COLUMN new_id BIGINT GENERATED BY DEFAULT AS IDENTITY;
    CREATE TEMP TABLE map_nf AS SELECT id as old_id, new_id as new_id FROM public.notas_fiscais;

    ALTER TABLE public.critica ADD COLUMN new_nota_fiscal_id BIGINT;
    UPDATE public.critica SET new_nota_fiscal_id = m.new_id FROM map_nf m WHERE critica.nota_fiscal_id = m.old_id;

    ALTER TABLE public.critica DROP CONSTRAINT IF EXISTS transactions_nota_fiscal_id_fkey;
    ALTER TABLE public.critica DROP CONSTRAINT IF EXISTS critica_nota_fiscal_id_fkey;
    ALTER TABLE public.critica DROP COLUMN nota_fiscal_id;
    ALTER TABLE public.critica RENAME COLUMN new_nota_fiscal_id TO nota_fiscal_id;

    ALTER TABLE public.notas_fiscais DROP CONSTRAINT notas_fiscais_pkey;
    ALTER TABLE public.notas_fiscais DROP COLUMN id;
    ALTER TABLE public.notas_fiscais RENAME COLUMN new_id TO id;
    ALTER TABLE public.notas_fiscais ADD PRIMARY KEY (id);

    ALTER TABLE public.critica ADD CONSTRAINT critica_nota_fiscal_id_fkey
      FOREIGN KEY (nota_fiscal_id) REFERENCES public.notas_fiscais(id) ON DELETE SET NULL;

    DROP TABLE map_nf;
  END IF;
END $$;

-- razao (no inbound FKs to razao.id)
DO $$
BEGIN
  IF EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_schema = 'public' AND table_name = 'razao'
    AND column_name = 'id' AND data_type = 'uuid'
  ) THEN
    ALTER TABLE public.razao ADD COLUMN new_id BIGINT GENERATED BY DEFAULT AS IDENTITY;
    ALTER TABLE public.razao DROP CONSTRAINT razao_pkey;
    ALTER TABLE public.razao DROP COLUMN id;
    ALTER TABLE public.razao RENAME COLUMN new_id TO id;
    ALTER TABLE public.razao ADD PRIMARY KEY (id);
  END IF;
END $$;
