-- Convert UUID primary keys to sequential BIGINT for bancos, atividades, centro_custos, plano_contas

-- =============================================
-- bancos (no inbound FKs)
-- =============================================
DO $$
BEGIN
  IF EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_schema = 'public' AND table_name = 'bancos'
    AND column_name = 'id' AND data_type = 'uuid'
  ) THEN
    ALTER TABLE public.bancos ADD COLUMN new_id BIGINT GENERATED BY DEFAULT AS IDENTITY;
    ALTER TABLE public.bancos DROP CONSTRAINT bancos_pkey;
    ALTER TABLE public.bancos DROP COLUMN id;
    ALTER TABLE public.bancos RENAME COLUMN new_id TO id;
    ALTER TABLE public.bancos ADD PRIMARY KEY (id);
  END IF;
END $$;

-- =============================================
-- atividades (inbound FK from critica.atividade_id)
-- =============================================
DO $$
BEGIN
  IF EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_schema = 'public' AND table_name = 'atividades'
    AND column_name = 'id' AND data_type = 'uuid'
  ) THEN
    ALTER TABLE public.atividades ADD COLUMN new_id BIGINT GENERATED BY DEFAULT AS IDENTITY;
    CREATE TEMP TABLE map_ativ AS SELECT id as old_id, new_id as new_id FROM public.atividades;

    ALTER TABLE public.critica ADD COLUMN new_atividade_id BIGINT;
    UPDATE public.critica SET new_atividade_id = m.new_id FROM map_ativ m WHERE critica.atividade_id = m.old_id;
    ALTER TABLE public.critica DROP CONSTRAINT IF EXISTS transactions_atividade_id_fkey;
    ALTER TABLE public.critica DROP CONSTRAINT IF EXISTS critica_atividade_id_fkey;
    ALTER TABLE public.critica DROP COLUMN atividade_id;
    ALTER TABLE public.critica RENAME COLUMN new_atividade_id TO atividade_id;

    ALTER TABLE public.atividades DROP CONSTRAINT atividades_pkey;
    ALTER TABLE public.atividades DROP COLUMN id;
    ALTER TABLE public.atividades RENAME COLUMN new_id TO id;
    ALTER TABLE public.atividades ADD PRIMARY KEY (id);

    ALTER TABLE public.critica ADD CONSTRAINT critica_atividade_id_fkey
      FOREIGN KEY (atividade_id) REFERENCES public.atividades(id) ON DELETE SET NULL;
    DROP TABLE map_ativ;
  END IF;
END $$;

-- =============================================
-- centro_custos (inbound FK from critica.centro_custo_id)
-- =============================================
DO $$
BEGIN
  IF EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_schema = 'public' AND table_name = 'centro_custos'
    AND column_name = 'id' AND data_type = 'uuid'
  ) THEN
    ALTER TABLE public.centro_custos ADD COLUMN new_id BIGINT GENERATED BY DEFAULT AS IDENTITY;
    CREATE TEMP TABLE map_cc AS SELECT id as old_id, new_id as new_id FROM public.centro_custos;

    ALTER TABLE public.critica ADD COLUMN new_centro_custo_id BIGINT;
    UPDATE public.critica SET new_centro_custo_id = m.new_id FROM map_cc m WHERE critica.centro_custo_id = m.old_id;
    ALTER TABLE public.critica DROP CONSTRAINT IF EXISTS transactions_centro_custo_id_fkey;
    ALTER TABLE public.critica DROP CONSTRAINT IF EXISTS critica_centro_custo_id_fkey;
    ALTER TABLE public.critica DROP COLUMN centro_custo_id;
    ALTER TABLE public.critica RENAME COLUMN new_centro_custo_id TO centro_custo_id;

    ALTER TABLE public.centro_custos DROP CONSTRAINT centro_custos_pkey;
    ALTER TABLE public.centro_custos DROP COLUMN id;
    ALTER TABLE public.centro_custos RENAME COLUMN new_id TO id;
    ALTER TABLE public.centro_custos ADD PRIMARY KEY (id);

    ALTER TABLE public.critica ADD CONSTRAINT critica_centro_custo_id_fkey
      FOREIGN KEY (centro_custo_id) REFERENCES public.centro_custos(id) ON DELETE SET NULL;
    DROP TABLE map_cc;
  END IF;
END $$;

-- =============================================
-- plano_contas (inbound FKs from critica.plano_conta_id and razao.plano_conta_id)
-- =============================================
DO $$
BEGIN
  IF EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_schema = 'public' AND table_name = 'plano_contas'
    AND column_name = 'id' AND data_type = 'uuid'
  ) THEN
    ALTER TABLE public.plano_contas ADD COLUMN new_id BIGINT GENERATED BY DEFAULT AS IDENTITY;
    CREATE TEMP TABLE map_pc AS SELECT id as old_id, new_id as new_id FROM public.plano_contas;

    -- Update critica.plano_conta_id
    ALTER TABLE public.critica ADD COLUMN new_plano_conta_id BIGINT;
    UPDATE public.critica SET new_plano_conta_id = m.new_id FROM map_pc m WHERE critica.plano_conta_id = m.old_id;
    ALTER TABLE public.critica DROP CONSTRAINT IF EXISTS transactions_plano_conta_id_fkey;
    ALTER TABLE public.critica DROP CONSTRAINT IF EXISTS critica_plano_conta_id_fkey;
    ALTER TABLE public.critica DROP COLUMN plano_conta_id;
    ALTER TABLE public.critica RENAME COLUMN new_plano_conta_id TO plano_conta_id;

    -- Update razao.plano_conta_id
    ALTER TABLE public.razao ADD COLUMN new_plano_conta_id BIGINT;
    UPDATE public.razao SET new_plano_conta_id = m.new_id FROM map_pc m WHERE razao.plano_conta_id = m.old_id;
    ALTER TABLE public.razao DROP CONSTRAINT IF EXISTS razao_plano_conta_id_fkey;
    ALTER TABLE public.razao DROP COLUMN plano_conta_id;
    ALTER TABLE public.razao RENAME COLUMN new_plano_conta_id TO plano_conta_id;

    -- Update plano_contas table
    ALTER TABLE public.plano_contas DROP CONSTRAINT plano_contas_pkey;
    ALTER TABLE public.plano_contas DROP COLUMN id;
    ALTER TABLE public.plano_contas RENAME COLUMN new_id TO id;
    ALTER TABLE public.plano_contas ADD PRIMARY KEY (id);

    -- Recreate FKs
    ALTER TABLE public.critica ADD CONSTRAINT critica_plano_conta_id_fkey
      FOREIGN KEY (plano_conta_id) REFERENCES public.plano_contas(id) ON DELETE SET NULL;
    ALTER TABLE public.razao ADD CONSTRAINT razao_plano_conta_id_fkey
      FOREIGN KEY (plano_conta_id) REFERENCES public.plano_contas(id) ON DELETE SET NULL;
    DROP TABLE map_pc;
  END IF;
END $$;
