-- Create extratos_bancarios table with RLS and seed data

CREATE TABLE IF NOT EXISTS public.extratos_bancarios (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,
  data DATE NOT NULL,
  descricao TEXT NOT NULL,
  valor NUMERIC NOT NULL,
  tipo TEXT NOT NULL CHECK (tipo IN ('debit', 'credit')),
  banco_id BIGINT REFERENCES public.bancos(id) ON DELETE CASCADE NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE public.extratos_bancarios ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "extratos_select" ON public.extratos_bancarios;
CREATE POLICY "extratos_select" ON public.extratos_bancarios
  FOR SELECT TO authenticated USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "extratos_insert" ON public.extratos_bancarios;
CREATE POLICY "extratos_insert" ON public.extratos_bancarios
  FOR INSERT TO authenticated WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "extratos_update" ON public.extratos_bancarios;
CREATE POLICY "extratos_update" ON public.extratos_bancarios
  FOR UPDATE TO authenticated USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "extratos_delete" ON public.extratos_bancarios;
CREATE POLICY "extratos_delete" ON public.extratos_bancarios
  FOR DELETE TO authenticated USING (auth.uid() = user_id);

CREATE INDEX IF NOT EXISTS extratos_bancarios_user_id_idx ON public.extratos_bancarios(user_id);
CREATE INDEX IF NOT EXISTS extratos_bancarios_banco_id_idx ON public.extratos_bancarios(banco_id);

-- Seed: 3 dummy transactions per bank account
DO $$
DECLARE
  b RECORD;
BEGIN
  FOR b IN SELECT id, user_id FROM public.bancos LOOP
    INSERT INTO public.extratos_bancarios (user_id, banco_id, data, descricao, valor, tipo) VALUES
      (b.user_id, b.id, '2026-06-15', 'Deposito em conta', 5000.00, 'credit'),
      (b.user_id, b.id, '2026-06-18', 'Pagamento de fornecedor', 1500.00, 'debit'),
      (b.user_id, b.id, '2026-06-22', 'Transferencia recebida', 2500.00, 'credit')
    ON CONFLICT DO NOTHING;
  END LOOP;
END $$;
